// Customer list generated from the Select Equip service-report corpus
// (docs_manifest.csv — clients with >=2 indexed reports), 10 Jul 2026.
// Regenerate when the corpus is re-ingested; keep sorted case-insensitively.
export const CUSTOMERS = [
  "4 Legs Pet Foods",
  "Alligator Brands",
  "AMG",
  "Andrews Meats",
  "Ausfresh",
  "Australian Country Choice",
  "Bangalow Pork",
  "Barden Produce",
  "Bartter Enterprises",
  "BE Campbell",
  "Beak & Johnston - Greenacre",
  "Bega Cheese",
  "Bel & Brio",
  "Bindaree Beef",
  "BodyFoodz",
  "Canon Foods (Hellers)",
  "Catalano Seafoods",
  "Chef Fresh",
  "Clean Health",
  "Coles RROA",
  "Community Chef (Western Health)",
  "Concept Beverages",
  "Cordina",
  "Costa Group",
  "Daily Chef WA",
  "Daily Chef-Vesco WA",
  "DBC",
  "De Costi",
  "DJays Gourmet",
  "Drakes",
  "Epicurean",
  "Farm Foods",
  "Genobile Saba (Gourmet Saba)",
  "Golden Cockeral",
  "Gourmet Meals (Wutrich Pty Ltd)",
  "GPI",
  "GWF (Don-KRC)",
  "Harris Smokehouse",
  "Harvey Beef",
  "Havericks Meats",
  "Hazeldene Chickens",
  "Heinz",
  "Hewitt Foods (Arcadian Meats, Cleavers)",
  "Hilton Foods",
  "Huon Aquaculture",
  "Inghams",
  "J.L King",
  "JBS",
  "Kilcoy",
  "LCDF",
  "Lite N Easy",
  "Luv A Duck",
  "Marathon Foods",
  "Master Catering",
  "McCains",
  "Mitchells Quality Foods",
  "My Muscle Chef",
  "Norfolk Foods (Rogue)",
  "Northern Import and Export Group NMPS",
  "Patchetts Pies",
  "Patties Foods VIC",
  "Patties SA (AWF - Australian Wholefoods)",
  "Patties WA (Vesco)",
  "Peters Poultry",
  "PFD Foods",
  "Premier Beehive",
  "Primo Foods",
  "RJ CUA",
  "Roma Foods",
  "Saizeriya",
  "Simplot",
  "SnapFresh",
  "Teys Foods - Tamworth - Abar line",
  "Teys Foods - Wagga",
  "The Curry Tree",
  "The Kitchenary Pty Ltd - Arndell Park (B&J City Kitchen)",
  "Thomas Foods NSW",
  "Thomas Foods VIC",
  "Tip Top Butchers",
  "Turosi-Golden Farms",
  "VegPro4",
  "VIP PetFoods",
  "Viscount Pooling Systems",
  "VIVERI PTY LTD T.A CUCINA CLASSICA",
  "Well & Good Bakery - Lafer",
  "Wide Open Agriculture",
  "Wrights the Butchers",
  "YouFoodz",
  "Yumis Foods",
  "Zags China",
];
